version: '3.7'

services: 
    ghpage:
        build:
            context: .
        image: ramneek/umbersar-site
        command: "bundle exec jekyll serve --config _config.yml --host 0.0.0.0 --drafts --incremental --force_polling"
        volumes:
            # - ${PWD}:/srv/jekyll
            - C:/Users/sin17h/Documents/umbersar.github.io:/srv/jekyll
        ports: 
            - "0.0.0.0:4000:4000"


#docker-compose up
#as the local directory is mapped in docker container, make changes locally and they would be reflected in the container. The 
#changes would then be served at http://localhost:4000/