version: '3.7'

services: 
    ghpage:
        build:
            context: .
        image: ramneek/umbersar-site
        command: "bundle exec jekyll serve --config _config.yml --host 0.0.0.0 --drafts --incremental --force_polling"
        volumes:
            # - ${PWD}:/srv/jekyll
            # - "$PWD":/srv/jekyll
            # - C:/Users/sin17h/Documents/umbersar.github.io:/srv/jekyll
            - .:/srv/jekyll
        ports: 
            - "0.0.0.0:4000:4000"


#docker-compose up
#as the local directory is mapped in docker container, make changes locally and they would be reflected in the container. The 
#changes would then be served at http://localhost:4000/
#The newly added posts might not reflect on the home page running in the docker container(or under the posts menu item) but if
# you directly access the URL (for example :http://localhost:4000/blog/unexpected_constant_folding_sql_server/), they 
# would be there.